server:
  port: 8080

spring:
  application:
    name: product-service
  devtools:
    livereload:
      port: 35730
  datasource:
    url: jdbc:mysql://194.31.52.65:3306/xnarx
    username: root
    password: Cool2002!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          jdbc:
            time_zone: Asia/Tashkent
    open-in-view: false
  sql:
    init:
      mode: never
  jackson:
    serialization:
      fail-on-empty-beans: false
    time-zone: Asia/Tashkent
  mail:
    host: smtp.gmail.com
    port: 587
    username: xnarxuz@gmail.com
    password: your_email_password
    protocol: smtp

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000



